apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - reverb-deployment.yaml
  - horizon-deployment.yaml
  - scheduler-cronjob.yaml
  - minio-deployment.yaml
  - meilisearch-deployment.yaml
  - redis-deployment.yaml
  - postgres-deployment.yaml
  - laravel.yaml
